### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by BaltiYoussef** [Wozzify/Snapchat-Memory-Downloader#1]
Hello,
I've tried using your code, when i copied your code and executed it on the safari terminal, it showed me this error. TypeError: 'undefined' is not a function (evaluating 'a.click()')
![image](https://user-images.githubusercontent.com/55838785/79574931-3eddfb00-80c1-11ea-811f-c9895d5bd2c3.png)

**Comment by Wozzify** [comment]
Hello!
So the first thing I'm going to ask is the data that you requested from Snapchat fresh and up to date? (Within the last three days) I have just requested my data from Snapchat again.

Have you tried to download any of the files manually just by 'clicking' the 'download' button ?

**Comment by Wozzify** [comment]
So I managed to request my Data again, after pasting the code I'm not having any problems. Are you sure your request data is a new file and not old?

Just so I can close this case!

Thanks.

<img width="1020" alt="Screenshot 2020-04-17 at 16 28 31" src="https://user-images.githubusercontent.com/63321091/79586121-9df33e00-80c8-11ea-9551-08fa44e01a92.png">

**Comment by BaltiYoussef** [comment]
I requested the data from snapchat today.
Then i downloaded Safari ( I have Windows 10). Yes you are right , i just checked .. i couldn't download the data manually on safari. I don't know what's wrong. Maybe it's not the right version of Safari. But on Google Chrome i can do it manually. Is there a way to download it from Chrome , or can you help me know the origin of this problem? Thank you

**Comment by Wozzify** [comment]
Yes, so that's good its fresh data.
I didn't realise you are on windows. Your best bet is using Firefox, and accessing the console via that. As Opera doesn't easily allow multiple files.

Let me know if Firefox works, it works on my mac!

**Comment by BaltiYoussef** [comment]
It worked! Thanks a lot!
