### ISSUE TITLE
Failed to load resource 

### ISSUE THREAD

**Issue by dishwasherpossum** [Wozzify/Snapchat-Memory-Downloader#10]
I'm not extremely tech savvy when it comes to GitHub or Mac, so my apologies if this is dumb. I'm using the code with safari, through download #1-90 ish I would frequently get the error:

"Failed to load resource: the server responded with a status of 500 ()" 

The downloads continued seamlessly by the looks of it, currently on download 300 and haven't got the error again. 

Either way, Thanks so much for this, relieved to have all my memories in hand.

**Comment by Wozzify** [comment]
Hey bud, sorry for the slow reply, didn't get an email notification about it.

Sounds to be like snapchat was playing up, has it all worked now ?

No worries! Great to get it out of the ecosystem.
