### ISSUE TITLE
Coding noob but really want to get this working

### ISSUE THREAD

**Issue by NikoV5** [Wozzify/Snapchat-Memory-Downloader#11]
Hello. So I'm not good with all of this code stuff but really need my memories backed up with dates/times so is there anyway you can make a tutorial video on how to do this on Mac or break it down for someone like me to understand? If it's in video format I should be able to figure it out no problem but this is my only option considering Snapchat makes it impossible to efficiently back up your memories

**Comment by Wozzify** [comment]
Hello,

So in regards to the EXIF data being taken, referring to the original post :

“ There also seems to be an issue with some EXIF data being pruned from certain files on a seemingly arbitrary basis.”

Essentially some data is lost due to Snapchat, but some remains, I haven’t been able to figure out why.

What part are you stuck at ?

**Comment by NikoV5** [comment]
I actually ended up figuring it out. Thanks for the super fast reply though! Glad your willing to help out in a proactive manner!

**Comment by Wozzify** [comment]
Excellent, let me know if you need a hand with anything, I am planning on rewriting it to make it even more user friendly…

**Comment by NikoV5** [comment]
Actually I do have a question about requesting data from Snapchat. So I noticed that when I requested my data from Snapchat some of the dates were wrong (which I was expecting but atleast they got the correct month anyway) but what suprised me is that some of the text captions from post were missing. Is this normal? Do I need to request my data again?

**Comment by Wozzify** [comment]
Hello,

I do have a similar issue, you could try and request the data again, but I think sometimes it just gets lost from Snapchats server, as all this script does is, downloads what Snapchat has available
