### ISSUE TITLE
K

### ISSUE THREAD

**Issue by layzaz** [Wozzify/Snapchat-Memory-Downloader#2]
https://app.snapchat.com/dmd/memories?uid=c8629261-4e17-4f5c-b3eb-b95ee2e0f35e&sid=5148CB40-3BFF-49F9-AD0D-73211C4BF21D&mid=5148CB40-3BFF-49F9-AD0D-73211C4BF21D&ts=1594275232827&proxy=true&sig=2a44872c1efe143b94584a451f67dd71e64610e5dd64fae6526165f0ec1b7dbf

**Comment by Wozzify** [comment]
> https://app.snapchat.com/dmd/memories?uid=c8629261-4e17-4f5c-b3eb-b95ee2e0f35e&sid=5148CB40-3BFF-49F9-AD0D-73211C4BF21D&mid=5148CB40-3BFF-49F9-AD0D-73211C4BF21D&ts=1594275232827&proxy=true&sig=2a44872c1efe143b94584a451f67dd71e64610e5dd64fae6526165f0ec1b7dbf


Hello! This happens when the link expires. You will need to ask Snapchat for a new download link.
Let me know if it works :)
