### ISSUE TITLE
Windows 10, Safari 5.1.7 -- TypeError: 'undefined' is not a function (evaluating 'a.click()') 

### ISSUE THREAD

**Issue by razzmatazzbuckshank** [Wozzify/Snapchat-Memory-Downloader#3]
I don't have a Mac, so this is the best I can do on Windows. I'm using Develop -> Show Error Console and pasting the code, but every time the code runs, it just gives me that error. Any ideas?

**Comment by Wozzify** [comment]
Hello, I am currently out of the house at the moment so wouldn’t be able to load up the VM until I’m home, but have you tried it on dare I say it (Microsoft edge) let me know if you make any progress and when I’m home I’ll hopefully be able to give you a hand...

**Comment by razzmatazzbuckshank** [comment]
On Microsoft Edge it says
```
Uncaught TypeError: Cannot read property 'href' of undefined
at download (<anonymous>:9:20)
at <anonymous>:21:1
```
I tried doing a bootleg solution on Chrome by downloading an autoclicker program to click "Allow" really quickly when running the script, but that wasn't working either lol. It didn't seem like Chrome was registering the program's clicks

**Comment by Wozzify** [comment]
I have just requested a new download link from Snapchat. I will boot up my VM and see what happens when I try and recreate it, it might be different browsers change certain aspects. Ill update you soon

**Comment by Wozzify** [comment]
So the thing is, if you open the page (on Microsoft edge) and then right-click and press inspect then press console. if you paste it in there it works, but Microsoft Edge doesn't allow multiple downloads. From what I have seen no one seems to allow multiple except Safari, but maybe another web browser would work, I'll look into it for you.
