### ISSUE TITLE
noob

### ISSUE THREAD

**Issue by flowergirlrose** [Wozzify/Snapchat-Memory-Downloader#4]
I have no idea what im doing. would you be able to help me out?

**Comment by Wozzify** [comment]
Hello,

What exactly are you stuck with ?

Have you requested your data from Snapchat yet ?

**Comment by flowergirlrose** [comment]
I have my data from snapchat. what do I do after that? when I click on the snapchatdownloader it opens up on my Mac in dreamweaver. what should I open it in and what should I type in

**Comment by Wozzify** [comment]
So once it’s downloaded, you open up the .HTML file in Safari or Chrome, then go to memories section. And then open up the safari console and paste the code.

Let me know if you need more help 👍

**Comment by flowergirlrose** [comment]
YAY I DID IT thank you so much

**Comment by flowergirlrose** [comment]
ugh I F-ed up..... I accidentally exited out of safari in the middle of the downloading

**Comment by Wozzify** [comment]
Uh oh. Any idea what number it got to ? If not just delete them all and restart and make sure your power settings don’t turn computer off !

Glad I could help, though.

**Comment by flowergirlrose** [comment]
I just restarted! thank you <3

**Comment by flowergirlrose** [comment]
if i do end up stopping it on accident, what do i do? plug in the number it started with somewhere?

**Comment by Wozzify** [comment]
So say if you stop at 1500 downloads,

When you want to start again you type in the variable “Go” to the number “1500”

`var go = 1500;`

Let me know if you need any more help, or I will be closing the Issue!

**Comment by flowergirlrose** [comment]
thank you so much! do you have a paypal or anything?

**Comment by Wozzify** [comment]
Only my personal PayPal, so no unfortunately.

I’m a firm believer that :

A. Snapchat should already have this (but they want to keep you in their ecosystem)

B. This should be completely free, I managed to download thousands of photos and videos, which were extremely sentimental to me.

Make sure you let people know about it!

Have a lovely day, @flowergirlrose
