### ISSUE TITLE
Doesn't work for video, please fix!

### ISSUE THREAD

**Issue by EnricoUniverse** [Wozzify/Snapchat-Memory-Downloader#8]
On Firefox it just opens the video. Could you make a fix for firefox? Or for chrome? Because safari for windows is cancelled.

**Comment by Wozzify** [comment]
Hey man, I realised that many people use Google Chrome,

its 3:00 AM at the moment, I will hopefully sort it out later today,

Many thanks.

**Comment by EnricoUniverse** [comment]
I tried doing something myself (not an expert by any means) and I fixed chrome snapchat downloading.

```
// Snapchat-Memory Downloader

var go = 36;
//0 is the start number

function download(){
    var links = document.getElementsByTagName("table")[0].getElementsByTagName("a");
    //Finds all of the "download" button entities and putting them under the variable 'links'
    document.links[go].click();
    //Is evaluating the download button with the variable 0 so you start off with the first one
    go++;
    //Makes the variable 0 go up in 1 increment everytime it gets to this part
    console.log(go);
    //Keeps progress of how many downloads you have initated (Can run behind if you have it on a high setting)
    setTimeout(download, 5000);
    //If you don't have a timeout it will just try and download all of them at once. This is the optimum speed but obviously
    //feel free to increase or decrease.
    //it starts the script again every 5 seconds so you have plenty of time to download the files.
    };

download();
```

The only thing that's in the way now is that Chrome keeps blocking multiple downloads. Which I can't seem to fix. Firefox doesn't block multiple downloads, but in Firefox when opening a video link, it doesn't download it straight away. So I think fixing it for Firefox could be easier, if there is some way to check for if it's a video and in that case change the method.

**Comment by EnricoUniverse** [comment]
Fixed it by changing a hidden setting in Firefox that makes it so that mp4s are downloaded instead of previewed on opening.

about:config -> media.play-stand-alone = FALSE

**Comment by Wozzify** [comment]
Hello, Just updated it to work on Chrome.

Looks like disabled Eval.

It works on Firefox if you have the auto open disabled,

Let me know if you need anything else.
